name: hisob_roject
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  easy_localization: ^3.0.8
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/i18n/
    - assets/images/
